services:
    - type: web
      name: patgroup-workspace
      env: node
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
